Added LDAP configuration and some small bugfixes
Sabai-Technologies/seafile-docker pull request #2
Opened 2018-04-12 11:28 UTC by zsoerenm

I added a possibility to configure LDAP using environment variables.
More information on this here: https://manual.seafile.com/deploy/using_ldap.html

A small bugfix: 
I moved `wait_for_db` out of  `if [[ ! -e $LATEST_SERVER_DIR ]]` so that it always runs on startup.
Otherwise `docker-compose down` and `docker-compose up` resulted in an error that mysql was not up.

Moreover I fixed the docker-compose example from `./seafile:/home/seafile` to `./seafile:/seafile`

2018-04-14 21:36 UTC, camory requested changes
Thank you for this Pull Request.
You can also add in the **FEATURE** part in the README.md that LDAP connection can be configured with environment variables.
I will merge it as soon as you have updated the Pull Request

2018-04-14 21:36 UTC, camory commented on README.md
> +  * **SEAFILE_LDAP_URL** (optional): LDAP URL (e.g. ldap://openldap)
it would be better that the name of these variables does not start with **SEAFILE_**

2018-04-14 21:36 UTC, camory commented on README.md
> +#       - SEAFILE_LDAP_URL=ldap://openldap
You can uncomment these lines.

2018-04-15 16:47 UTC, zsoerenm commented
Requested changes are implemented

2018-04-15 21:12 UTC, camory approved these changes

2018-04-15 21:14 UTC, merged

2018-04-16 06:45 UTC, zsoerenm commented
Thanks, could that be tagged on docker hub?
https://hub.docker.com/r/sabaitech/seafile/tags/

2018-04-19 10:57 UTC, camory commented
It has been tagged with latest :)

2018-04-19 12:27 UTC, zsoerenm commented
Sure, but I'd like to have a version number so that I am able to increase the version number when I like to ;)

2018-04-24 21:42 UTC, camory commented
I have just updated the way to manage version. It is a first throw, we will see if we need to update it.
So the tag for this feature is 6.1.2-1